version: '3.7'

services:
  discord-bot:
    container_name: ustar_travel-bot
    image: ustar_travel/helper
    build:
      context: .
      target: build
    restart: always
    tty: true
    command: npm run start
    volumes:
      - .:/build/
      - node_modules:/build/node_modules
    ports:
      - "${PORT:-4013}:${PORT:-4042}"
    depends_on:
      - db
    networks:
      - default
    env_file: .env
  db:
    container_name: ustar_travel-db
    image: postgis/postgis:12-3.0-alpine
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - ${DEV_DB_PORT:-4012}:4012
    env_file: .env
    networks:
      - default
      - localnet
    environment:
      PGHOST: ""

networks:
  localnet:

volumes:
  node_modules:
  db-data:
